# Generated by Django 5.1.4 on 2026-07-13 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.CharField(max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, help_text='Relationship with the worker (Self/Wife/Son...)', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='DBTBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSED', 'Processed')], default='OPEN', max_length=12)),
            ],
            options={
                'verbose_name_plural': 'DBT batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
                ('scheme_type', models.CharField(default='WELFARE', max_length=40)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DBTPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('failure_reason', models.CharField(blank=True, max_length=150)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.application')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.dbtbatch')),
                ('retry_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='portal.dbtpayment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ALOCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.district')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Mandal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandals', to='portal.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SubScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('required_fields', models.TextField(blank=True, help_text='Pipe-separated form fields & documents')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subschemes', to='portal.scheme')),
            ],
            options={
                'ordering': ['scheme__code', 'code'],
                'unique_together': {('scheme', 'code')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='subscheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.subscheme'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('mandal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='portal.mandal')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('mandal', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('employer_name', models.CharField(help_text='Owner / responsible person', max_length=120)),
                ('category', models.CharField(choices=[('BUILDER', 'Builder'), ('CONTRACTOR', 'Contractor'), ('DEVELOPER', 'Developer'), ('GOVT_PROJECT', 'Government project'), ('OTHER', 'Other')], default='CONTRACTOR', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('est_workers_count', models.IntegerField(default=0, help_text='Declared number of workers')),
                ('cess_paid', models.DecimalField(decimal_places=2, default=0, help_text='Cess contribution to the welfare fund (₹)', max_digits=12)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishments', to='portal.village')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40, unique=True)),
                ('temp_id', models.CharField(blank=True, max_length=20)),
                ('alo_code', models.CharField(blank=True, max_length=10)),
                ('reg_year', models.IntegerField()),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('worker_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('worker_name_telugu', models.CharField(blank=True, max_length=200)),
                ('father_name_telugu', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('caste_code', models.CharField(blank=True, max_length=10)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('ifsc_valid', models.BooleanField(default=False)),
                ('trade_union_member', models.BooleanField(default=False)),
                ('migrant_worker', models.BooleanField(default=False)),
                ('trade_code', models.CharField(blank=True, max_length=10)),
                ('district_code', models.CharField(blank=True, max_length=10)),
                ('is_test_row', models.BooleanField(default=False)),
                ('age_flag', models.BooleanField(default=False)),
                ('valid_until', models.DateField(blank=True, help_text='Registration valid for 5 years; extended by approved renewals', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alo_circle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='portal.alocircle')),
                ('employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='portal.establishment')),
                ('village', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='portal.village')),
            ],
            options={
                'ordering': ['-reg_year', 'reg_no'],
            },
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.CharField(max_length=30, unique=True)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='portal.worker')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relationship', models.CharField(max_length=60)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('share_percent', models.IntegerField(default=100)),
                ('is_primary', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='portal.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_no', models.CharField(max_length=30, unique=True)),
                ('request_type', models.CharField(choices=[('NAME_CHANGE', 'Name change'), ('NOMINEE_CHANGE', 'Nominee change'), ('BANK_CHANGE', 'Bank/IFSC change')], max_length=20)),
                ('old_value', models.CharField(blank=True, max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='portal.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.worker'),
        ),
    ]
