# Generated by Django 5.1.4 on 2026-07-12 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=200)),
                ('scheme_type', models.CharField(default='WELFARE', max_length=40)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40, unique=True)),
                ('temp_id', models.CharField(blank=True, max_length=20)),
                ('alo_code', models.CharField(blank=True, max_length=10)),
                ('reg_year', models.IntegerField()),
                ('reg_date', models.DateField(blank=True, null=True)),
                ('worker_name', models.CharField(max_length=120)),
                ('father_name', models.CharField(blank=True, max_length=120)),
                ('worker_name_telugu', models.CharField(blank=True, max_length=200)),
                ('father_name_telugu', models.CharField(blank=True, max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('caste_code', models.CharField(blank=True, max_length=10)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('ifsc_valid', models.BooleanField(default=False)),
                ('trade_union_member', models.BooleanField(default=False)),
                ('migrant_worker', models.BooleanField(default=False)),
                ('trade_code', models.CharField(blank=True, max_length=10)),
                ('district_code', models.CharField(blank=True, max_length=10)),
                ('is_test_row', models.BooleanField(default=False)),
                ('age_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reg_year', 'reg_no'],
            },
        ),
        migrations.CreateModel(
            name='SubScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('required_fields', models.TextField(blank=True, help_text='Pipe-separated form fields & documents')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subschemes', to='portal.scheme')),
            ],
            options={
                'ordering': ['scheme__code', 'code'],
                'unique_together': {('scheme', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_no', models.CharField(max_length=30, unique=True)),
                ('applicant_name', models.CharField(max_length=120)),
                ('relationship', models.CharField(blank=True, help_text='Relationship with the worker (Self/Wife/Son...)', max_length=60)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('bank_account', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=15)),
                ('remarks', models.CharField(blank=True, max_length=250)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('subscheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.subscheme')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='portal.worker')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
