# Generated by Django 5.1.4 on 2026-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='benefit_amount',
            field=models.CharField(blank=True, help_text='Sanctioned amount (sample value for demo)', max_length=120),
        ),
        migrations.AddField(
            model_name='scheme',
            name='eligibility',
            field=models.TextField(blank=True, help_text='Who can apply for this scheme'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='procedure',
            field=models.TextField(blank=True, help_text='Steps to be followed for applying'),
        ),
    ]
